# Generated by Django 4.1.4 on 2023-02-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todoitem",
            options={"ordering": ["due_date"]},
        ),
    ]
